version: '3.8'
services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ["-h", "0.0.0.0"]
    ports:
      - "8545:8545"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - ganache
    environment:
      BLOCKCHAIN_ADDRESS: "http://ganache:8545"

